-- Auto-generated from src/lib/kana-data.ts by scripts/generate-seed.mjs.
-- Regenerate with: npm run seed:generate

insert into public.learning_items (
  id,
  script_type,
  character,
  romaji,
  meaning_en,
  meaning_vi,
  note_en,
  note_vi,
  lesson_group,
  subgroup,
  vowel_group,
  sort_order,
  is_enabled
)
values
  ('hiragana_a_a', 'hiragana', 'あ', 'a', 'a', 'a', 'Pronounced as "a".', 'Phát âm là "a".', 'a', 'basic', 'a', 0, true),
  ('hiragana_a_i', 'hiragana', 'い', 'i', 'i', 'i', 'Pronounced as "i".', 'Phát âm là "i".', 'a', 'basic', 'i', 1, true),
  ('hiragana_a_u', 'hiragana', 'う', 'u', 'u', 'u', 'Pronounced as "u".', 'Phát âm là "u".', 'a', 'basic', 'u', 2, true),
  ('hiragana_a_e', 'hiragana', 'え', 'e', 'e', 'e', 'Pronounced as "e".', 'Phát âm là "e".', 'a', 'basic', 'e', 3, true),
  ('hiragana_a_o', 'hiragana', 'お', 'o', 'o', 'o', 'Pronounced as "o".', 'Phát âm là "o".', 'a', 'basic', 'o', 4, true),
  ('hiragana_ka_ka', 'hiragana', 'か', 'ka', 'ka', 'ka', 'Pronounced as "ka".', 'Phát âm là "ka".', 'ka', 'basic', 'a', 5, true),
  ('hiragana_ka_ki', 'hiragana', 'き', 'ki', 'ki', 'ki', 'Pronounced as "ki".', 'Phát âm là "ki".', 'ka', 'basic', 'i', 6, true),
  ('hiragana_ka_ku', 'hiragana', 'く', 'ku', 'ku', 'ku', 'Pronounced as "ku".', 'Phát âm là "ku".', 'ka', 'basic', 'u', 7, true),
  ('hiragana_ka_ke', 'hiragana', 'け', 'ke', 'ke', 'ke', 'Pronounced as "ke".', 'Phát âm là "ke".', 'ka', 'basic', 'e', 8, true),
  ('hiragana_ka_ko', 'hiragana', 'こ', 'ko', 'ko', 'ko', 'Pronounced as "ko".', 'Phát âm là "ko".', 'ka', 'basic', 'o', 9, true),
  ('hiragana_sa_sa', 'hiragana', 'さ', 'sa', 'sa', 'sa', 'Pronounced as "sa".', 'Phát âm là "sa".', 'sa', 'basic', 'a', 10, true),
  ('hiragana_sa_shi', 'hiragana', 'し', 'shi', 'shi', 'shi', 'Pronounced as "shi".', 'Phát âm là "shi".', 'sa', 'basic', 'i', 11, true),
  ('hiragana_sa_su', 'hiragana', 'す', 'su', 'su', 'su', 'Pronounced as "su".', 'Phát âm là "su".', 'sa', 'basic', 'u', 12, true),
  ('hiragana_sa_se', 'hiragana', 'せ', 'se', 'se', 'se', 'Pronounced as "se".', 'Phát âm là "se".', 'sa', 'basic', 'e', 13, true),
  ('hiragana_sa_so', 'hiragana', 'そ', 'so', 'so', 'so', 'Pronounced as "so".', 'Phát âm là "so".', 'sa', 'basic', 'o', 14, true),
  ('hiragana_ta_ta', 'hiragana', 'た', 'ta', 'ta', 'ta', 'Pronounced as "ta".', 'Phát âm là "ta".', 'ta', 'basic', 'a', 15, true),
  ('hiragana_ta_chi', 'hiragana', 'ち', 'chi', 'chi', 'chi', 'Pronounced as "chi".', 'Phát âm là "chi".', 'ta', 'basic', 'i', 16, true),
  ('hiragana_ta_tsu', 'hiragana', 'つ', 'tsu', 'tsu', 'tsu', 'Pronounced as "tsu".', 'Phát âm là "tsu".', 'ta', 'basic', 'u', 17, true),
  ('hiragana_ta_te', 'hiragana', 'て', 'te', 'te', 'te', 'Pronounced as "te".', 'Phát âm là "te".', 'ta', 'basic', 'e', 18, true),
  ('hiragana_ta_to', 'hiragana', 'と', 'to', 'to', 'to', 'Pronounced as "to".', 'Phát âm là "to".', 'ta', 'basic', 'o', 19, true),
  ('hiragana_na_na', 'hiragana', 'な', 'na', 'na', 'na', 'Pronounced as "na".', 'Phát âm là "na".', 'na', 'basic', 'a', 20, true),
  ('hiragana_na_ni', 'hiragana', 'に', 'ni', 'ni', 'ni', 'Pronounced as "ni".', 'Phát âm là "ni".', 'na', 'basic', 'i', 21, true),
  ('hiragana_na_nu', 'hiragana', 'ぬ', 'nu', 'nu', 'nu', 'Pronounced as "nu".', 'Phát âm là "nu".', 'na', 'basic', 'u', 22, true),
  ('hiragana_na_ne', 'hiragana', 'ね', 'ne', 'ne', 'ne', 'Pronounced as "ne".', 'Phát âm là "ne".', 'na', 'basic', 'e', 23, true),
  ('hiragana_na_no', 'hiragana', 'の', 'no', 'no', 'no', 'Pronounced as "no".', 'Phát âm là "no".', 'na', 'basic', 'o', 24, true),
  ('hiragana_ha_ha', 'hiragana', 'は', 'ha', 'ha', 'ha', 'Pronounced as "ha".', 'Phát âm là "ha".', 'ha', 'basic', 'a', 25, true),
  ('hiragana_ha_hi', 'hiragana', 'ひ', 'hi', 'hi', 'hi', 'Pronounced as "hi".', 'Phát âm là "hi".', 'ha', 'basic', 'i', 26, true),
  ('hiragana_ha_fu', 'hiragana', 'ふ', 'fu', 'fu', 'fu', 'Pronounced as "fu".', 'Phát âm là "fu".', 'ha', 'basic', 'u', 27, true),
  ('hiragana_ha_he', 'hiragana', 'へ', 'he', 'he', 'he', 'Pronounced as "he".', 'Phát âm là "he".', 'ha', 'basic', 'e', 28, true),
  ('hiragana_ha_ho', 'hiragana', 'ほ', 'ho', 'ho', 'ho', 'Pronounced as "ho".', 'Phát âm là "ho".', 'ha', 'basic', 'o', 29, true),
  ('hiragana_ma_ma', 'hiragana', 'ま', 'ma', 'ma', 'ma', 'Pronounced as "ma".', 'Phát âm là "ma".', 'ma', 'basic', 'a', 30, true),
  ('hiragana_ma_mi', 'hiragana', 'み', 'mi', 'mi', 'mi', 'Pronounced as "mi".', 'Phát âm là "mi".', 'ma', 'basic', 'i', 31, true),
  ('hiragana_ma_mu', 'hiragana', 'む', 'mu', 'mu', 'mu', 'Pronounced as "mu".', 'Phát âm là "mu".', 'ma', 'basic', 'u', 32, true),
  ('hiragana_ma_me', 'hiragana', 'め', 'me', 'me', 'me', 'Pronounced as "me".', 'Phát âm là "me".', 'ma', 'basic', 'e', 33, true),
  ('hiragana_ma_mo', 'hiragana', 'も', 'mo', 'mo', 'mo', 'Pronounced as "mo".', 'Phát âm là "mo".', 'ma', 'basic', 'o', 34, true),
  ('hiragana_ya_ya', 'hiragana', 'や', 'ya', 'ya', 'ya', 'Pronounced as "ya".', 'Phát âm là "ya".', 'ya', 'basic', 'a', 35, true),
  ('hiragana_ya_yu', 'hiragana', 'ゆ', 'yu', 'yu', 'yu', 'Pronounced as "yu".', 'Phát âm là "yu".', 'ya', 'basic', 'u', 36, true),
  ('hiragana_ya_yo', 'hiragana', 'よ', 'yo', 'yo', 'yo', 'Pronounced as "yo".', 'Phát âm là "yo".', 'ya', 'basic', 'o', 37, true),
  ('hiragana_ra_ra', 'hiragana', 'ら', 'ra', 'ra', 'ra', 'Pronounced as "ra".', 'Phát âm là "ra".', 'ra', 'basic', 'a', 38, true),
  ('hiragana_ra_ri', 'hiragana', 'り', 'ri', 'ri', 'ri', 'Pronounced as "ri".', 'Phát âm là "ri".', 'ra', 'basic', 'i', 39, true),
  ('hiragana_ra_ru', 'hiragana', 'る', 'ru', 'ru', 'ru', 'Pronounced as "ru".', 'Phát âm là "ru".', 'ra', 'basic', 'u', 40, true),
  ('hiragana_ra_re', 'hiragana', 'れ', 're', 're', 're', 'Pronounced as "re".', 'Phát âm là "re".', 'ra', 'basic', 'e', 41, true),
  ('hiragana_ra_ro', 'hiragana', 'ろ', 'ro', 'ro', 'ro', 'Pronounced as "ro".', 'Phát âm là "ro".', 'ra', 'basic', 'o', 42, true),
  ('hiragana_wa_wa', 'hiragana', 'わ', 'wa', 'wa', 'wa', 'Pronounced as "wa".', 'Phát âm là "wa".', 'wa', 'basic', 'a', 43, true),
  ('hiragana_wa_wo', 'hiragana', 'を', 'wo', 'wo', 'wo', 'Pronounced as "wo".', 'Phát âm là "wo".', 'wa', 'basic', 'o', 44, true),
  ('hiragana_wa_n', 'hiragana', 'ん', 'n', 'n', 'n', 'Pronounced as "n".', 'Phát âm là "n".', 'wa', 'basic', 'special', 45, true),
  ('hiragana_ga_ga', 'hiragana', 'が', 'ga', 'ga', 'ga', 'Pronounced as "ga".', 'Phát âm là "ga".', 'ga', 'dakuten', 'a', 100, true),
  ('hiragana_ga_gi', 'hiragana', 'ぎ', 'gi', 'gi', 'gi', 'Pronounced as "gi".', 'Phát âm là "gi".', 'ga', 'dakuten', 'i', 101, true),
  ('hiragana_ga_gu', 'hiragana', 'ぐ', 'gu', 'gu', 'gu', 'Pronounced as "gu".', 'Phát âm là "gu".', 'ga', 'dakuten', 'u', 102, true),
  ('hiragana_ga_ge', 'hiragana', 'げ', 'ge', 'ge', 'ge', 'Pronounced as "ge".', 'Phát âm là "ge".', 'ga', 'dakuten', 'e', 103, true),
  ('hiragana_ga_go', 'hiragana', 'ご', 'go', 'go', 'go', 'Pronounced as "go".', 'Phát âm là "go".', 'ga', 'dakuten', 'o', 104, true),
  ('hiragana_za_za', 'hiragana', 'ざ', 'za', 'za', 'za', 'Pronounced as "za".', 'Phát âm là "za".', 'za', 'dakuten', 'a', 105, true),
  ('hiragana_za_ji', 'hiragana', 'じ', 'ji', 'ji', 'ji', 'Pronounced as "ji".', 'Phát âm là "ji".', 'za', 'dakuten', 'i', 106, true),
  ('hiragana_za_zu', 'hiragana', 'ず', 'zu', 'zu', 'zu', 'Pronounced as "zu".', 'Phát âm là "zu".', 'za', 'dakuten', 'u', 107, true),
  ('hiragana_za_ze', 'hiragana', 'ぜ', 'ze', 'ze', 'ze', 'Pronounced as "ze".', 'Phát âm là "ze".', 'za', 'dakuten', 'e', 108, true),
  ('hiragana_za_zo', 'hiragana', 'ぞ', 'zo', 'zo', 'zo', 'Pronounced as "zo".', 'Phát âm là "zo".', 'za', 'dakuten', 'o', 109, true),
  ('hiragana_da_da', 'hiragana', 'だ', 'da', 'da', 'da', 'Pronounced as "da".', 'Phát âm là "da".', 'da', 'dakuten', 'a', 110, true),
  ('hiragana_da_ji', 'hiragana', 'ぢ', 'ji', 'ji', 'ji', 'Pronounced as "ji".', 'Phát âm là "ji".', 'da', 'dakuten', 'i', 111, true),
  ('hiragana_da_zu', 'hiragana', 'づ', 'zu', 'zu', 'zu', 'Pronounced as "zu".', 'Phát âm là "zu".', 'da', 'dakuten', 'u', 112, true),
  ('hiragana_da_de', 'hiragana', 'で', 'de', 'de', 'de', 'Pronounced as "de".', 'Phát âm là "de".', 'da', 'dakuten', 'e', 113, true),
  ('hiragana_da_do', 'hiragana', 'ど', 'do', 'do', 'do', 'Pronounced as "do".', 'Phát âm là "do".', 'da', 'dakuten', 'o', 114, true),
  ('hiragana_ba_ba', 'hiragana', 'ば', 'ba', 'ba', 'ba', 'Pronounced as "ba".', 'Phát âm là "ba".', 'ba', 'dakuten', 'a', 115, true),
  ('hiragana_ba_bi', 'hiragana', 'び', 'bi', 'bi', 'bi', 'Pronounced as "bi".', 'Phát âm là "bi".', 'ba', 'dakuten', 'i', 116, true),
  ('hiragana_ba_bu', 'hiragana', 'ぶ', 'bu', 'bu', 'bu', 'Pronounced as "bu".', 'Phát âm là "bu".', 'ba', 'dakuten', 'u', 117, true),
  ('hiragana_ba_be', 'hiragana', 'べ', 'be', 'be', 'be', 'Pronounced as "be".', 'Phát âm là "be".', 'ba', 'dakuten', 'e', 118, true),
  ('hiragana_ba_bo', 'hiragana', 'ぼ', 'bo', 'bo', 'bo', 'Pronounced as "bo".', 'Phát âm là "bo".', 'ba', 'dakuten', 'o', 119, true),
  ('hiragana_pa_pa', 'hiragana', 'ぱ', 'pa', 'pa', 'pa', 'Pronounced as "pa".', 'Phát âm là "pa".', 'pa', 'handakuten', 'a', 120, true),
  ('hiragana_pa_pi', 'hiragana', 'ぴ', 'pi', 'pi', 'pi', 'Pronounced as "pi".', 'Phát âm là "pi".', 'pa', 'handakuten', 'i', 121, true),
  ('hiragana_pa_pu', 'hiragana', 'ぷ', 'pu', 'pu', 'pu', 'Pronounced as "pu".', 'Phát âm là "pu".', 'pa', 'handakuten', 'u', 122, true),
  ('hiragana_pa_pe', 'hiragana', 'ぺ', 'pe', 'pe', 'pe', 'Pronounced as "pe".', 'Phát âm là "pe".', 'pa', 'handakuten', 'e', 123, true),
  ('hiragana_pa_po', 'hiragana', 'ぽ', 'po', 'po', 'po', 'Pronounced as "po".', 'Phát âm là "po".', 'pa', 'handakuten', 'o', 124, true),
  ('hiragana_kya_kya', 'hiragana', 'きゃ', 'kya', 'kya', 'kya', 'Pronounced as "kya".', 'Phát âm là "kya".', 'kya', 'youon', 'a', 200, true),
  ('hiragana_kya_kyu', 'hiragana', 'きゅ', 'kyu', 'kyu', 'kyu', 'Pronounced as "kyu".', 'Phát âm là "kyu".', 'kya', 'youon', 'u', 201, true),
  ('hiragana_kya_kyo', 'hiragana', 'きょ', 'kyo', 'kyo', 'kyo', 'Pronounced as "kyo".', 'Phát âm là "kyo".', 'kya', 'youon', 'o', 202, true),
  ('hiragana_sha_sha', 'hiragana', 'しゃ', 'sha', 'sha', 'sha', 'Pronounced as "sha".', 'Phát âm là "sha".', 'sha', 'youon', 'a', 203, true),
  ('hiragana_sha_shu', 'hiragana', 'しゅ', 'shu', 'shu', 'shu', 'Pronounced as "shu".', 'Phát âm là "shu".', 'sha', 'youon', 'u', 204, true),
  ('hiragana_sha_sho', 'hiragana', 'しょ', 'sho', 'sho', 'sho', 'Pronounced as "sho".', 'Phát âm là "sho".', 'sha', 'youon', 'o', 205, true),
  ('hiragana_cha_cha', 'hiragana', 'ちゃ', 'cha', 'cha', 'cha', 'Pronounced as "cha".', 'Phát âm là "cha".', 'cha', 'youon', 'a', 206, true),
  ('hiragana_cha_chu', 'hiragana', 'ちゅ', 'chu', 'chu', 'chu', 'Pronounced as "chu".', 'Phát âm là "chu".', 'cha', 'youon', 'u', 207, true),
  ('hiragana_cha_cho', 'hiragana', 'ちょ', 'cho', 'cho', 'cho', 'Pronounced as "cho".', 'Phát âm là "cho".', 'cha', 'youon', 'o', 208, true),
  ('hiragana_nya_nya', 'hiragana', 'にゃ', 'nya', 'nya', 'nya', 'Pronounced as "nya".', 'Phát âm là "nya".', 'nya', 'youon', 'a', 209, true),
  ('hiragana_nya_nyu', 'hiragana', 'にゅ', 'nyu', 'nyu', 'nyu', 'Pronounced as "nyu".', 'Phát âm là "nyu".', 'nya', 'youon', 'u', 210, true),
  ('hiragana_nya_nyo', 'hiragana', 'にょ', 'nyo', 'nyo', 'nyo', 'Pronounced as "nyo".', 'Phát âm là "nyo".', 'nya', 'youon', 'o', 211, true),
  ('hiragana_hya_hya', 'hiragana', 'ひゃ', 'hya', 'hya', 'hya', 'Pronounced as "hya".', 'Phát âm là "hya".', 'hya', 'youon', 'a', 212, true),
  ('hiragana_hya_hyu', 'hiragana', 'ひゅ', 'hyu', 'hyu', 'hyu', 'Pronounced as "hyu".', 'Phát âm là "hyu".', 'hya', 'youon', 'u', 213, true),
  ('hiragana_hya_hyo', 'hiragana', 'ひょ', 'hyo', 'hyo', 'hyo', 'Pronounced as "hyo".', 'Phát âm là "hyo".', 'hya', 'youon', 'o', 214, true),
  ('hiragana_mya_mya', 'hiragana', 'みゃ', 'mya', 'mya', 'mya', 'Pronounced as "mya".', 'Phát âm là "mya".', 'mya', 'youon', 'a', 215, true),
  ('hiragana_mya_myu', 'hiragana', 'みゅ', 'myu', 'myu', 'myu', 'Pronounced as "myu".', 'Phát âm là "myu".', 'mya', 'youon', 'u', 216, true),
  ('hiragana_mya_myo', 'hiragana', 'みょ', 'myo', 'myo', 'myo', 'Pronounced as "myo".', 'Phát âm là "myo".', 'mya', 'youon', 'o', 217, true),
  ('hiragana_rya_rya', 'hiragana', 'りゃ', 'rya', 'rya', 'rya', 'Pronounced as "rya".', 'Phát âm là "rya".', 'rya', 'youon', 'a', 218, true),
  ('hiragana_rya_ryu', 'hiragana', 'りゅ', 'ryu', 'ryu', 'ryu', 'Pronounced as "ryu".', 'Phát âm là "ryu".', 'rya', 'youon', 'u', 219, true),
  ('hiragana_rya_ryo', 'hiragana', 'りょ', 'ryo', 'ryo', 'ryo', 'Pronounced as "ryo".', 'Phát âm là "ryo".', 'rya', 'youon', 'o', 220, true),
  ('hiragana_gya_gya', 'hiragana', 'ぎゃ', 'gya', 'gya', 'gya', 'Pronounced as "gya".', 'Phát âm là "gya".', 'gya', 'youon', 'a', 221, true),
  ('hiragana_gya_gyu', 'hiragana', 'ぎゅ', 'gyu', 'gyu', 'gyu', 'Pronounced as "gyu".', 'Phát âm là "gyu".', 'gya', 'youon', 'u', 222, true),
  ('hiragana_gya_gyo', 'hiragana', 'ぎょ', 'gyo', 'gyo', 'gyo', 'Pronounced as "gyo".', 'Phát âm là "gyo".', 'gya', 'youon', 'o', 223, true),
  ('hiragana_ja_ja', 'hiragana', 'じゃ', 'ja', 'ja', 'ja', 'Pronounced as "ja".', 'Phát âm là "ja".', 'ja', 'youon', 'a', 224, true),
  ('hiragana_ja_ju', 'hiragana', 'じゅ', 'ju', 'ju', 'ju', 'Pronounced as "ju".', 'Phát âm là "ju".', 'ja', 'youon', 'u', 225, true),
  ('hiragana_ja_jo', 'hiragana', 'じょ', 'jo', 'jo', 'jo', 'Pronounced as "jo".', 'Phát âm là "jo".', 'ja', 'youon', 'o', 226, true),
  ('hiragana_bya_bya', 'hiragana', 'びゃ', 'bya', 'bya', 'bya', 'Pronounced as "bya".', 'Phát âm là "bya".', 'bya', 'youon', 'a', 227, true),
  ('hiragana_bya_byu', 'hiragana', 'びゅ', 'byu', 'byu', 'byu', 'Pronounced as "byu".', 'Phát âm là "byu".', 'bya', 'youon', 'u', 228, true),
  ('hiragana_bya_byo', 'hiragana', 'びょ', 'byo', 'byo', 'byo', 'Pronounced as "byo".', 'Phát âm là "byo".', 'bya', 'youon', 'o', 229, true),
  ('hiragana_pya_pya', 'hiragana', 'ぴゃ', 'pya', 'pya', 'pya', 'Pronounced as "pya".', 'Phát âm là "pya".', 'pya', 'youon', 'a', 230, true),
  ('hiragana_pya_pyu', 'hiragana', 'ぴゅ', 'pyu', 'pyu', 'pyu', 'Pronounced as "pyu".', 'Phát âm là "pyu".', 'pya', 'youon', 'u', 231, true),
  ('hiragana_pya_pyo', 'hiragana', 'ぴょ', 'pyo', 'pyo', 'pyo', 'Pronounced as "pyo".', 'Phát âm là "pyo".', 'pya', 'youon', 'o', 232, true),
  ('hiragana_sokuon_small_tsu', 'hiragana', 'っ', 'small tsu', 'small tsu', 'tsu nhỏ', 'Marks a doubled consonant in the next sound.', 'Báo hiệu âm phụ âm kép ở âm tiết tiếp theo.', 'sokuon', 'sokuon', 'special', 300, true),
  ('hiragana_long_vowel_ou', 'hiragana', 'おう', 'ou', 'ou', 'ou', 'Pronounced as "ou".', 'Phát âm là "ou".', 'long_vowel', 'long_vowel', 'u', 301, true),
  ('hiragana_long_vowel_ei', 'hiragana', 'えい', 'ei', 'ei', 'ei', 'Pronounced as "ei".', 'Phát âm là "ei".', 'long_vowel', 'long_vowel', 'i', 302, true),
  ('katakana_a_a', 'katakana', 'ア', 'a', 'a', 'a', 'Pronounced as "a".', 'Phát âm là "a".', 'a', 'basic', 'a', 400, true),
  ('katakana_a_i', 'katakana', 'イ', 'i', 'i', 'i', 'Pronounced as "i".', 'Phát âm là "i".', 'a', 'basic', 'i', 401, true),
  ('katakana_a_u', 'katakana', 'ウ', 'u', 'u', 'u', 'Pronounced as "u".', 'Phát âm là "u".', 'a', 'basic', 'u', 402, true),
  ('katakana_a_e', 'katakana', 'エ', 'e', 'e', 'e', 'Pronounced as "e".', 'Phát âm là "e".', 'a', 'basic', 'e', 403, true),
  ('katakana_a_o', 'katakana', 'オ', 'o', 'o', 'o', 'Pronounced as "o".', 'Phát âm là "o".', 'a', 'basic', 'o', 404, true),
  ('katakana_ka_ka', 'katakana', 'カ', 'ka', 'ka', 'ka', 'Pronounced as "ka".', 'Phát âm là "ka".', 'ka', 'basic', 'a', 405, true),
  ('katakana_ka_ki', 'katakana', 'キ', 'ki', 'ki', 'ki', 'Pronounced as "ki".', 'Phát âm là "ki".', 'ka', 'basic', 'i', 406, true),
  ('katakana_ka_ku', 'katakana', 'ク', 'ku', 'ku', 'ku', 'Pronounced as "ku".', 'Phát âm là "ku".', 'ka', 'basic', 'u', 407, true),
  ('katakana_ka_ke', 'katakana', 'ケ', 'ke', 'ke', 'ke', 'Pronounced as "ke".', 'Phát âm là "ke".', 'ka', 'basic', 'e', 408, true),
  ('katakana_ka_ko', 'katakana', 'コ', 'ko', 'ko', 'ko', 'Pronounced as "ko".', 'Phát âm là "ko".', 'ka', 'basic', 'o', 409, true),
  ('katakana_sa_sa', 'katakana', 'サ', 'sa', 'sa', 'sa', 'Pronounced as "sa".', 'Phát âm là "sa".', 'sa', 'basic', 'a', 410, true),
  ('katakana_sa_shi', 'katakana', 'シ', 'shi', 'shi', 'shi', 'Pronounced as "shi".', 'Phát âm là "shi".', 'sa', 'basic', 'i', 411, true),
  ('katakana_sa_su', 'katakana', 'ス', 'su', 'su', 'su', 'Pronounced as "su".', 'Phát âm là "su".', 'sa', 'basic', 'u', 412, true),
  ('katakana_sa_se', 'katakana', 'セ', 'se', 'se', 'se', 'Pronounced as "se".', 'Phát âm là "se".', 'sa', 'basic', 'e', 413, true),
  ('katakana_sa_so', 'katakana', 'ソ', 'so', 'so', 'so', 'Pronounced as "so".', 'Phát âm là "so".', 'sa', 'basic', 'o', 414, true),
  ('katakana_ta_ta', 'katakana', 'タ', 'ta', 'ta', 'ta', 'Pronounced as "ta".', 'Phát âm là "ta".', 'ta', 'basic', 'a', 415, true),
  ('katakana_ta_chi', 'katakana', 'チ', 'chi', 'chi', 'chi', 'Pronounced as "chi".', 'Phát âm là "chi".', 'ta', 'basic', 'i', 416, true),
  ('katakana_ta_tsu', 'katakana', 'ツ', 'tsu', 'tsu', 'tsu', 'Pronounced as "tsu".', 'Phát âm là "tsu".', 'ta', 'basic', 'u', 417, true),
  ('katakana_ta_te', 'katakana', 'テ', 'te', 'te', 'te', 'Pronounced as "te".', 'Phát âm là "te".', 'ta', 'basic', 'e', 418, true),
  ('katakana_ta_to', 'katakana', 'ト', 'to', 'to', 'to', 'Pronounced as "to".', 'Phát âm là "to".', 'ta', 'basic', 'o', 419, true),
  ('katakana_na_na', 'katakana', 'ナ', 'na', 'na', 'na', 'Pronounced as "na".', 'Phát âm là "na".', 'na', 'basic', 'a', 420, true),
  ('katakana_na_ni', 'katakana', 'ニ', 'ni', 'ni', 'ni', 'Pronounced as "ni".', 'Phát âm là "ni".', 'na', 'basic', 'i', 421, true),
  ('katakana_na_nu', 'katakana', 'ヌ', 'nu', 'nu', 'nu', 'Pronounced as "nu".', 'Phát âm là "nu".', 'na', 'basic', 'u', 422, true),
  ('katakana_na_ne', 'katakana', 'ネ', 'ne', 'ne', 'ne', 'Pronounced as "ne".', 'Phát âm là "ne".', 'na', 'basic', 'e', 423, true),
  ('katakana_na_no', 'katakana', 'ノ', 'no', 'no', 'no', 'Pronounced as "no".', 'Phát âm là "no".', 'na', 'basic', 'o', 424, true),
  ('katakana_ha_ha', 'katakana', 'ハ', 'ha', 'ha', 'ha', 'Pronounced as "ha".', 'Phát âm là "ha".', 'ha', 'basic', 'a', 425, true),
  ('katakana_ha_hi', 'katakana', 'ヒ', 'hi', 'hi', 'hi', 'Pronounced as "hi".', 'Phát âm là "hi".', 'ha', 'basic', 'i', 426, true),
  ('katakana_ha_fu', 'katakana', 'フ', 'fu', 'fu', 'fu', 'Pronounced as "fu".', 'Phát âm là "fu".', 'ha', 'basic', 'u', 427, true),
  ('katakana_ha_he', 'katakana', 'ヘ', 'he', 'he', 'he', 'Pronounced as "he".', 'Phát âm là "he".', 'ha', 'basic', 'e', 428, true),
  ('katakana_ha_ho', 'katakana', 'ホ', 'ho', 'ho', 'ho', 'Pronounced as "ho".', 'Phát âm là "ho".', 'ha', 'basic', 'o', 429, true),
  ('katakana_ma_ma', 'katakana', 'マ', 'ma', 'ma', 'ma', 'Pronounced as "ma".', 'Phát âm là "ma".', 'ma', 'basic', 'a', 430, true),
  ('katakana_ma_mi', 'katakana', 'ミ', 'mi', 'mi', 'mi', 'Pronounced as "mi".', 'Phát âm là "mi".', 'ma', 'basic', 'i', 431, true),
  ('katakana_ma_mu', 'katakana', 'ム', 'mu', 'mu', 'mu', 'Pronounced as "mu".', 'Phát âm là "mu".', 'ma', 'basic', 'u', 432, true),
  ('katakana_ma_me', 'katakana', 'メ', 'me', 'me', 'me', 'Pronounced as "me".', 'Phát âm là "me".', 'ma', 'basic', 'e', 433, true),
  ('katakana_ma_mo', 'katakana', 'モ', 'mo', 'mo', 'mo', 'Pronounced as "mo".', 'Phát âm là "mo".', 'ma', 'basic', 'o', 434, true),
  ('katakana_ya_ya', 'katakana', 'ヤ', 'ya', 'ya', 'ya', 'Pronounced as "ya".', 'Phát âm là "ya".', 'ya', 'basic', 'a', 435, true),
  ('katakana_ya_yu', 'katakana', 'ユ', 'yu', 'yu', 'yu', 'Pronounced as "yu".', 'Phát âm là "yu".', 'ya', 'basic', 'u', 436, true),
  ('katakana_ya_yo', 'katakana', 'ヨ', 'yo', 'yo', 'yo', 'Pronounced as "yo".', 'Phát âm là "yo".', 'ya', 'basic', 'o', 437, true),
  ('katakana_ra_ra', 'katakana', 'ラ', 'ra', 'ra', 'ra', 'Pronounced as "ra".', 'Phát âm là "ra".', 'ra', 'basic', 'a', 438, true),
  ('katakana_ra_ri', 'katakana', 'リ', 'ri', 'ri', 'ri', 'Pronounced as "ri".', 'Phát âm là "ri".', 'ra', 'basic', 'i', 439, true),
  ('katakana_ra_ru', 'katakana', 'ル', 'ru', 'ru', 'ru', 'Pronounced as "ru".', 'Phát âm là "ru".', 'ra', 'basic', 'u', 440, true),
  ('katakana_ra_re', 'katakana', 'レ', 're', 're', 're', 'Pronounced as "re".', 'Phát âm là "re".', 'ra', 'basic', 'e', 441, true),
  ('katakana_ra_ro', 'katakana', 'ロ', 'ro', 'ro', 'ro', 'Pronounced as "ro".', 'Phát âm là "ro".', 'ra', 'basic', 'o', 442, true),
  ('katakana_wa_wa', 'katakana', 'ワ', 'wa', 'wa', 'wa', 'Pronounced as "wa".', 'Phát âm là "wa".', 'wa', 'basic', 'a', 443, true),
  ('katakana_wa_wo', 'katakana', 'ヲ', 'wo', 'wo', 'wo', 'Pronounced as "wo".', 'Phát âm là "wo".', 'wa', 'basic', 'o', 444, true),
  ('katakana_wa_n', 'katakana', 'ン', 'n', 'n', 'n', 'Pronounced as "n".', 'Phát âm là "n".', 'wa', 'basic', 'special', 445, true),
  ('katakana_ga_ga', 'katakana', 'ガ', 'ga', 'ga', 'ga', 'Pronounced as "ga".', 'Phát âm là "ga".', 'ga', 'dakuten', 'a', 500, true),
  ('katakana_ga_gi', 'katakana', 'ギ', 'gi', 'gi', 'gi', 'Pronounced as "gi".', 'Phát âm là "gi".', 'ga', 'dakuten', 'i', 501, true),
  ('katakana_ga_gu', 'katakana', 'グ', 'gu', 'gu', 'gu', 'Pronounced as "gu".', 'Phát âm là "gu".', 'ga', 'dakuten', 'u', 502, true),
  ('katakana_ga_ge', 'katakana', 'ゲ', 'ge', 'ge', 'ge', 'Pronounced as "ge".', 'Phát âm là "ge".', 'ga', 'dakuten', 'e', 503, true),
  ('katakana_ga_go', 'katakana', 'ゴ', 'go', 'go', 'go', 'Pronounced as "go".', 'Phát âm là "go".', 'ga', 'dakuten', 'o', 504, true),
  ('katakana_za_za', 'katakana', 'ザ', 'za', 'za', 'za', 'Pronounced as "za".', 'Phát âm là "za".', 'za', 'dakuten', 'a', 505, true),
  ('katakana_za_ji', 'katakana', 'ジ', 'ji', 'ji', 'ji', 'Pronounced as "ji".', 'Phát âm là "ji".', 'za', 'dakuten', 'i', 506, true),
  ('katakana_za_zu', 'katakana', 'ズ', 'zu', 'zu', 'zu', 'Pronounced as "zu".', 'Phát âm là "zu".', 'za', 'dakuten', 'u', 507, true),
  ('katakana_za_ze', 'katakana', 'ゼ', 'ze', 'ze', 'ze', 'Pronounced as "ze".', 'Phát âm là "ze".', 'za', 'dakuten', 'e', 508, true),
  ('katakana_za_zo', 'katakana', 'ゾ', 'zo', 'zo', 'zo', 'Pronounced as "zo".', 'Phát âm là "zo".', 'za', 'dakuten', 'o', 509, true),
  ('katakana_da_da', 'katakana', 'ダ', 'da', 'da', 'da', 'Pronounced as "da".', 'Phát âm là "da".', 'da', 'dakuten', 'a', 510, true),
  ('katakana_da_ji', 'katakana', 'ヂ', 'ji', 'ji', 'ji', 'Pronounced as "ji".', 'Phát âm là "ji".', 'da', 'dakuten', 'i', 511, true),
  ('katakana_da_zu', 'katakana', 'ヅ', 'zu', 'zu', 'zu', 'Pronounced as "zu".', 'Phát âm là "zu".', 'da', 'dakuten', 'u', 512, true),
  ('katakana_da_de', 'katakana', 'デ', 'de', 'de', 'de', 'Pronounced as "de".', 'Phát âm là "de".', 'da', 'dakuten', 'e', 513, true),
  ('katakana_da_do', 'katakana', 'ド', 'do', 'do', 'do', 'Pronounced as "do".', 'Phát âm là "do".', 'da', 'dakuten', 'o', 514, true),
  ('katakana_ba_ba', 'katakana', 'バ', 'ba', 'ba', 'ba', 'Pronounced as "ba".', 'Phát âm là "ba".', 'ba', 'dakuten', 'a', 515, true),
  ('katakana_ba_bi', 'katakana', 'ビ', 'bi', 'bi', 'bi', 'Pronounced as "bi".', 'Phát âm là "bi".', 'ba', 'dakuten', 'i', 516, true),
  ('katakana_ba_bu', 'katakana', 'ブ', 'bu', 'bu', 'bu', 'Pronounced as "bu".', 'Phát âm là "bu".', 'ba', 'dakuten', 'u', 517, true),
  ('katakana_ba_be', 'katakana', 'ベ', 'be', 'be', 'be', 'Pronounced as "be".', 'Phát âm là "be".', 'ba', 'dakuten', 'e', 518, true),
  ('katakana_ba_bo', 'katakana', 'ボ', 'bo', 'bo', 'bo', 'Pronounced as "bo".', 'Phát âm là "bo".', 'ba', 'dakuten', 'o', 519, true),
  ('katakana_pa_pa', 'katakana', 'パ', 'pa', 'pa', 'pa', 'Pronounced as "pa".', 'Phát âm là "pa".', 'pa', 'handakuten', 'a', 520, true),
  ('katakana_pa_pi', 'katakana', 'ピ', 'pi', 'pi', 'pi', 'Pronounced as "pi".', 'Phát âm là "pi".', 'pa', 'handakuten', 'i', 521, true),
  ('katakana_pa_pu', 'katakana', 'プ', 'pu', 'pu', 'pu', 'Pronounced as "pu".', 'Phát âm là "pu".', 'pa', 'handakuten', 'u', 522, true),
  ('katakana_pa_pe', 'katakana', 'ペ', 'pe', 'pe', 'pe', 'Pronounced as "pe".', 'Phát âm là "pe".', 'pa', 'handakuten', 'e', 523, true),
  ('katakana_pa_po', 'katakana', 'ポ', 'po', 'po', 'po', 'Pronounced as "po".', 'Phát âm là "po".', 'pa', 'handakuten', 'o', 524, true),
  ('katakana_kya_kya', 'katakana', 'キャ', 'kya', 'kya', 'kya', 'Pronounced as "kya".', 'Phát âm là "kya".', 'kya', 'youon', 'a', 600, true),
  ('katakana_kya_kyu', 'katakana', 'キュ', 'kyu', 'kyu', 'kyu', 'Pronounced as "kyu".', 'Phát âm là "kyu".', 'kya', 'youon', 'u', 601, true),
  ('katakana_kya_kyo', 'katakana', 'キョ', 'kyo', 'kyo', 'kyo', 'Pronounced as "kyo".', 'Phát âm là "kyo".', 'kya', 'youon', 'o', 602, true),
  ('katakana_sha_sha', 'katakana', 'シャ', 'sha', 'sha', 'sha', 'Pronounced as "sha".', 'Phát âm là "sha".', 'sha', 'youon', 'a', 603, true),
  ('katakana_sha_shu', 'katakana', 'シュ', 'shu', 'shu', 'shu', 'Pronounced as "shu".', 'Phát âm là "shu".', 'sha', 'youon', 'u', 604, true),
  ('katakana_sha_sho', 'katakana', 'ショ', 'sho', 'sho', 'sho', 'Pronounced as "sho".', 'Phát âm là "sho".', 'sha', 'youon', 'o', 605, true),
  ('katakana_cha_cha', 'katakana', 'チャ', 'cha', 'cha', 'cha', 'Pronounced as "cha".', 'Phát âm là "cha".', 'cha', 'youon', 'a', 606, true),
  ('katakana_cha_chu', 'katakana', 'チュ', 'chu', 'chu', 'chu', 'Pronounced as "chu".', 'Phát âm là "chu".', 'cha', 'youon', 'u', 607, true),
  ('katakana_cha_cho', 'katakana', 'チョ', 'cho', 'cho', 'cho', 'Pronounced as "cho".', 'Phát âm là "cho".', 'cha', 'youon', 'o', 608, true),
  ('katakana_nya_nya', 'katakana', 'ニャ', 'nya', 'nya', 'nya', 'Pronounced as "nya".', 'Phát âm là "nya".', 'nya', 'youon', 'a', 609, true),
  ('katakana_nya_nyu', 'katakana', 'ニュ', 'nyu', 'nyu', 'nyu', 'Pronounced as "nyu".', 'Phát âm là "nyu".', 'nya', 'youon', 'u', 610, true),
  ('katakana_nya_nyo', 'katakana', 'ニョ', 'nyo', 'nyo', 'nyo', 'Pronounced as "nyo".', 'Phát âm là "nyo".', 'nya', 'youon', 'o', 611, true),
  ('katakana_hya_hya', 'katakana', 'ヒャ', 'hya', 'hya', 'hya', 'Pronounced as "hya".', 'Phát âm là "hya".', 'hya', 'youon', 'a', 612, true),
  ('katakana_hya_hyu', 'katakana', 'ヒュ', 'hyu', 'hyu', 'hyu', 'Pronounced as "hyu".', 'Phát âm là "hyu".', 'hya', 'youon', 'u', 613, true),
  ('katakana_hya_hyo', 'katakana', 'ヒョ', 'hyo', 'hyo', 'hyo', 'Pronounced as "hyo".', 'Phát âm là "hyo".', 'hya', 'youon', 'o', 614, true),
  ('katakana_mya_mya', 'katakana', 'ミャ', 'mya', 'mya', 'mya', 'Pronounced as "mya".', 'Phát âm là "mya".', 'mya', 'youon', 'a', 615, true),
  ('katakana_mya_myu', 'katakana', 'ミュ', 'myu', 'myu', 'myu', 'Pronounced as "myu".', 'Phát âm là "myu".', 'mya', 'youon', 'u', 616, true),
  ('katakana_mya_myo', 'katakana', 'ミョ', 'myo', 'myo', 'myo', 'Pronounced as "myo".', 'Phát âm là "myo".', 'mya', 'youon', 'o', 617, true),
  ('katakana_rya_rya', 'katakana', 'リャ', 'rya', 'rya', 'rya', 'Pronounced as "rya".', 'Phát âm là "rya".', 'rya', 'youon', 'a', 618, true),
  ('katakana_rya_ryu', 'katakana', 'リュ', 'ryu', 'ryu', 'ryu', 'Pronounced as "ryu".', 'Phát âm là "ryu".', 'rya', 'youon', 'u', 619, true),
  ('katakana_rya_ryo', 'katakana', 'リョ', 'ryo', 'ryo', 'ryo', 'Pronounced as "ryo".', 'Phát âm là "ryo".', 'rya', 'youon', 'o', 620, true),
  ('katakana_gya_gya', 'katakana', 'ギャ', 'gya', 'gya', 'gya', 'Pronounced as "gya".', 'Phát âm là "gya".', 'gya', 'youon', 'a', 621, true),
  ('katakana_gya_gyu', 'katakana', 'ギュ', 'gyu', 'gyu', 'gyu', 'Pronounced as "gyu".', 'Phát âm là "gyu".', 'gya', 'youon', 'u', 622, true),
  ('katakana_gya_gyo', 'katakana', 'ギョ', 'gyo', 'gyo', 'gyo', 'Pronounced as "gyo".', 'Phát âm là "gyo".', 'gya', 'youon', 'o', 623, true),
  ('katakana_ja_ja', 'katakana', 'ジャ', 'ja', 'ja', 'ja', 'Pronounced as "ja".', 'Phát âm là "ja".', 'ja', 'youon', 'a', 624, true),
  ('katakana_ja_ju', 'katakana', 'ジュ', 'ju', 'ju', 'ju', 'Pronounced as "ju".', 'Phát âm là "ju".', 'ja', 'youon', 'u', 625, true),
  ('katakana_ja_jo', 'katakana', 'ジョ', 'jo', 'jo', 'jo', 'Pronounced as "jo".', 'Phát âm là "jo".', 'ja', 'youon', 'o', 626, true),
  ('katakana_bya_bya', 'katakana', 'ビャ', 'bya', 'bya', 'bya', 'Pronounced as "bya".', 'Phát âm là "bya".', 'bya', 'youon', 'a', 627, true),
  ('katakana_bya_byu', 'katakana', 'ビュ', 'byu', 'byu', 'byu', 'Pronounced as "byu".', 'Phát âm là "byu".', 'bya', 'youon', 'u', 628, true),
  ('katakana_bya_byo', 'katakana', 'ビョ', 'byo', 'byo', 'byo', 'Pronounced as "byo".', 'Phát âm là "byo".', 'bya', 'youon', 'o', 629, true),
  ('katakana_pya_pya', 'katakana', 'ピャ', 'pya', 'pya', 'pya', 'Pronounced as "pya".', 'Phát âm là "pya".', 'pya', 'youon', 'a', 630, true),
  ('katakana_pya_pyu', 'katakana', 'ピュ', 'pyu', 'pyu', 'pyu', 'Pronounced as "pyu".', 'Phát âm là "pyu".', 'pya', 'youon', 'u', 631, true),
  ('katakana_pya_pyo', 'katakana', 'ピョ', 'pyo', 'pyo', 'pyo', 'Pronounced as "pyo".', 'Phát âm là "pyo".', 'pya', 'youon', 'o', 632, true),
  ('katakana_loanword-fa_fa', 'katakana', 'ファ', 'fa', 'fa', 'fa', 'Pronounced as "fa".', 'Phát âm là "fa".', 'loanword-fa', 'loanword', 'a', 633, true),
  ('katakana_loanword-fa_fi', 'katakana', 'フィ', 'fi', 'fi', 'fi', 'Pronounced as "fi".', 'Phát âm là "fi".', 'loanword-fa', 'loanword', 'i', 634, true),
  ('katakana_loanword-fa_fe', 'katakana', 'フェ', 'fe', 'fe', 'fe', 'Pronounced as "fe".', 'Phát âm là "fe".', 'loanword-fa', 'loanword', 'e', 635, true),
  ('katakana_loanword-fa_fo', 'katakana', 'フォ', 'fo', 'fo', 'fo', 'Pronounced as "fo".', 'Phát âm là "fo".', 'loanword-fa', 'loanword', 'o', 636, true),
  ('katakana_loanword-v_vi', 'katakana', 'ヴィ', 'vi', 'vi', 'vi', 'Pronounced as "vi".', 'Phát âm là "vi".', 'loanword-v', 'loanword', 'i', 637, true),
  ('katakana_loanword-v_ve', 'katakana', 'ヴェ', 've', 've', 've', 'Pronounced as "ve".', 'Phát âm là "ve".', 'loanword-v', 'loanword', 'e', 638, true),
  ('katakana_loanword-v_vo', 'katakana', 'ヴォ', 'vo', 'vo', 'vo', 'Pronounced as "vo".', 'Phát âm là "vo".', 'loanword-v', 'loanword', 'o', 639, true),
  ('katakana_loanword-w_wi', 'katakana', 'ウィ', 'wi', 'wi', 'wi', 'Pronounced as "wi".', 'Phát âm là "wi".', 'loanword-w', 'loanword', 'i', 640, true),
  ('katakana_loanword-w_we', 'katakana', 'ウェ', 'we', 'we', 'we', 'Pronounced as "we".', 'Phát âm là "we".', 'loanword-w', 'loanword', 'e', 641, true),
  ('katakana_loanword-w_wo', 'katakana', 'ウォ', 'wo', 'wo', 'wo', 'Pronounced as "wo".', 'Phát âm là "wo".', 'loanword-w', 'loanword', 'o', 642, true),
  ('katakana_loanword-ts_tsa', 'katakana', 'ツァ', 'tsa', 'tsa', 'tsa', 'Pronounced as "tsa".', 'Phát âm là "tsa".', 'loanword-ts', 'loanword', 'a', 643, true),
  ('katakana_loanword-ts_tsi', 'katakana', 'ツィ', 'tsi', 'tsi', 'tsi', 'Pronounced as "tsi".', 'Phát âm là "tsi".', 'loanword-ts', 'loanword', 'i', 644, true),
  ('katakana_loanword-ts_tse', 'katakana', 'ツェ', 'tse', 'tse', 'tse', 'Pronounced as "tse".', 'Phát âm là "tse".', 'loanword-ts', 'loanword', 'e', 645, true),
  ('katakana_loanword-ts_tso', 'katakana', 'ツォ', 'tso', 'tso', 'tso', 'Pronounced as "tso".', 'Phát âm là "tso".', 'loanword-ts', 'loanword', 'o', 646, true),
  ('katakana_loanword-t_ti', 'katakana', 'ティ', 'ti', 'ti', 'ti', 'Pronounced as "ti".', 'Phát âm là "ti".', 'loanword-t', 'loanword', 'i', 647, true),
  ('katakana_loanword-t_di', 'katakana', 'ディ', 'di', 'di', 'di', 'Pronounced as "di".', 'Phát âm là "di".', 'loanword-t', 'loanword', 'i', 648, true),
  ('katakana_loanword-t_tu', 'katakana', 'トゥ', 'tu', 'tu', 'tu', 'Pronounced as "tu".', 'Phát âm là "tu".', 'loanword-t', 'loanword', 'u', 649, true),
  ('katakana_loanword-t_du', 'katakana', 'ドゥ', 'du', 'du', 'du', 'Pronounced as "du".', 'Phát âm là "du".', 'loanword-t', 'loanword', 'u', 650, true),
  ('katakana_loanword-j_je', 'katakana', 'ジェ', 'je', 'je', 'je', 'Pronounced as "je".', 'Phát âm là "je".', 'loanword-j', 'loanword', 'e', 651, true),
  ('katakana_loanword-j_che', 'katakana', 'チェ', 'che', 'che', 'che', 'Pronounced as "che".', 'Phát âm là "che".', 'loanword-j', 'loanword', 'e', 652, true),
  ('katakana_loanword-j_she', 'katakana', 'シェ', 'she', 'she', 'she', 'Pronounced as "she".', 'Phát âm là "she".', 'loanword-j', 'loanword', 'e', 653, true),
  ('katakana_long_vowel_long_vowel_mark', 'katakana', 'ー', 'long vowel mark', 'long vowel mark', 'dấu kéo dài âm', 'Used mainly in Katakana loanwords to stretch a vowel.', 'Dùng chủ yếu trong Katakana để kéo dài nguyên âm của từ mượn.', 'long_vowel', 'long_vowel', 'special', 654, true)
on conflict (id) do update set
  script_type = excluded.script_type,
  character = excluded.character,
  romaji = excluded.romaji,
  meaning_en = excluded.meaning_en,
  meaning_vi = excluded.meaning_vi,
  note_en = excluded.note_en,
  note_vi = excluded.note_vi,
  lesson_group = excluded.lesson_group,
  subgroup = excluded.subgroup,
  vowel_group = excluded.vowel_group,
  sort_order = excluded.sort_order,
  is_enabled = excluded.is_enabled;
